version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - db-config.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
    container_name: flask-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

volumes:
  db-data: