version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=quotes_db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"

  app:
    build:
      context: .
    container_name: flask-app
    restart: always
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

volumes:
  mongo-data:
