apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: daily-quote
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: daily-quote
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-app
  type: ClusterIP